image: $CONTAINER_TEST_IMAGE

variables:
  CONTAINER_TEST_IMAGE: gitlab-registry.mpcdf.mpg.de/$CI_PROJECT_PATH:$CI_BUILD_REF_NAME

stages:
  - build_docker
  - testing
#  - demos
  - release

build_docker:
  image: docker
  stage: build_docker
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab-registry.mpcdf.mpg.de
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

test_gcc:
  stage: testing
  script:
    - python3 setup.py sdist
    - 'tar xvzf dist/ducc0*.tar.gz'
    - 'cd ducc0-* && python3 setup.py install --user && python3 -m pytest -q python/test'

test_clang:
  stage: testing
  script:
    - python3 setup.py sdist
    - 'tar xvzf dist/ducc0*.tar.gz'
    - 'cd ducc0-* && CC=clang CXX=clang++ python3 setup.py install --user && python3 -m pytest -q python/test'

test_rust:
  stage: testing
  image: rust:latest
  script:
    - cd rust && cargo build

#wgridding_demo:
#  stage: demos
#  script:
#    - python3 setup.py install --user -f && python3 python/demos/wgridder_python_implementations.py

release:
  stage: release
  script:
    - python3 setup.py sdist
    - 'mv dist/*.tar.gz .'
  artifacts:
    paths:
      - '*.tar.gz'

pages:
  stage: release
  script:
    - DUCC0_OPTIMIZATION=none python3 -m pip install --break-system-packages --user .
    - make -C doc html
    - 'cd src/doc && doxygen Doxyfile && cd ../..'
    - mv doc/build/html public
    - mv src/doc/build/html public/cpp
  artifacts:
    paths:
    - public
  only:
    - ducc0
